FROM nginx:stable-alpine

MAINTAINER cipchk <cipchk@qq.com>

COPY /usr/src/app/_nginx/default.conf /etc/nginx/conf.d/

RUN rm -rf /usr/share/nginx/html/*

COPY /usr/src/app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
