FROM node:10

MAINTAINER cipchk <cipchk@qq.com>

WORKDIR /usr/src/app

COPY package.json package.json

RUN /bin/sh -c 'npm config set registry https://registry.npm.taobao.org && npm config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass && npm i'

COPY . .

RUN npm run build

# deploy to github.io
RUN /bin/sh -c 'npm i --save-dev gh-pages && node ./node_modules/.bin/gh-pages -d dist -r "https://${NG_ALAIN_BUILDS_TOKEN}@github.com/ng-alain/ng-alain.git"'
