/*
 * Automatically generated by 'ng g ng-alain:plugin import'
 * @see https://ng-alain.com/cli/plugin#import
 */

import { G2BarModule } from '@delon/chart/bar';
import { G2PieModule } from '@delon/chart/pie';
import { G2MiniBarModule } from '@delon/chart/mini-bar';
import { G2TimelineModule } from '@delon/chart/timeline';
import { G2CardModule } from '@delon/chart/card';
import { G2MiniAreaModule } from '@delon/chart/mini-area';
import { TrendModule } from '@delon/chart/trend';
import { NumberInfoModule } from '@delon/chart/number-info';
import { G2WaterWaveModule } from '@delon/chart/water-wave';
import { G2MiniProgressModule } from '@delon/chart/mini-progress';
import { G2RadarModule } from '@delon/chart/radar';
import { DelonACLModule } from '@delon/acl';
import { DelonFormModule } from '@delon/form';
import { SidebarNavModule } from '@delon/abc/sidebar-nav';
import { NoticeIconModule } from '@delon/abc/notice-icon';
import { GlobalFooterModule } from '@delon/abc/global-footer';
import { G2GaugeModule } from '@delon/chart/gauge';
import { G2TagCloudModule } from '@delon/chart/tag-cloud';
import { QuickMenuModule } from '@delon/abc/quick-menu';
import { STModule } from '@delon/abc/table';
import { ResultModule } from '@delon/abc/result';
import { PageHeaderModule } from '@delon/abc/page-header';
import { CountDownModule } from '@delon/abc/count-down';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzDropDownModule } from 'ng-zorro-antd/dropdown';
import { NzAvatarModule } from 'ng-zorro-antd/avatar';
import { NzSwitchModule } from 'ng-zorro-antd/switch';
import { NzGridModule } from 'ng-zorro-antd/grid';
import { NzDrawerModule } from 'ng-zorro-antd/drawer';
import { NzDividerModule } from 'ng-zorro-antd/divider';
import { NzTabsModule } from 'ng-zorro-antd/tabs';
import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzToolTipModule } from 'ng-zorro-antd/tooltip';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzBadgeModule } from 'ng-zorro-antd/badge';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzInputNumberModule } from 'ng-zorro-antd/input-number';
import { NzListModule } from 'ng-zorro-antd/list';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import { NzRadioModule } from 'ng-zorro-antd/radio';
import { NzBreadCrumbModule } from 'ng-zorro-antd/breadcrumb';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzProgressModule } from 'ng-zorro-antd/progress';
import { NzPopconfirmModule } from 'ng-zorro-antd/popconfirm';
import { NzPopoverModule } from 'ng-zorro-antd/popover';
import { NzPaginationModule } from 'ng-zorro-antd/pagination';
import { NzMessageModule } from 'ng-zorro-antd/message';

export const DELON_MODULES = [
  G2CardModule,
  G2MiniAreaModule,
  G2RadarModule,
  G2PieModule,
  G2MiniProgressModule,
  G2WaterWaveModule,
  G2TagCloudModule,
  G2GaugeModule,
  TrendModule,
  NumberInfoModule,
  G2BarModule,
  G2TimelineModule,
  G2MiniBarModule,
  DelonACLModule,
  DelonFormModule,
  SidebarNavModule,
  NoticeIconModule,
  GlobalFooterModule,
  QuickMenuModule,
  STModule,
  CountDownModule,
  PageHeaderModule,
  ResultModule,
];

export const ZORRO_MODULES = [
  NzMessageModule,
  NzProgressModule,
  NzPopconfirmModule,
  NzPopoverModule,
  NzPaginationModule,
  NzIconModule,
  NzDropDownModule,
  NzAvatarModule,
  NzSwitchModule,
  NzGridModule,
  NzDrawerModule,
  NzDividerModule,
  NzTabsModule,
  NzAlertModule,
  NzToolTipModule,
  NzInputModule,
  NzInputNumberModule,
  NzCardModule,
  NzBadgeModule,
  NzSpinModule,
  NzListModule,
  NzDatePickerModule,
  NzRadioModule,
  NzBreadCrumbModule,
  NzButtonModule,
  NzFormModule,
  NzSelectModule,
];
